import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
let commit = process.env.GITHUB_SHA;
if (!commit) {
  try {
    commit = execFileSync('git', ['rev-parse', 'HEAD'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    commit = 'local-development';
  }
}
if (!/^(?:[0-9a-f]{40}|local-development)$/.test(commit)) throw new Error('Invalid build revision');
writeFileSync(
  'src/shared/build.ts',
  `// Generated by scripts/version.mjs. Contains no secrets.\nexport const COMMIT = ${JSON.stringify(commit)};\n`,
);
writeFileSync('public/version.json', JSON.stringify({ commit }) + '\n');
